name: x86-ubuntu

on:
  push:
    branches: [ "master", "dev" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: sudo apt-get install ninja-build

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ 

    - name: Build
      run: ninja -C ${{github.workspace}}/build test_runners

    - name: Run convolutional test 
      run: ${{github.workspace}}/build/tests/convolutional_test_runner

    - name: Run reed solomon test 
      run: ${{github.workspace}}/build/tests/reed_solomon_test_runner
